engines:
    phpcodesniffer:
        enabled: true
    phpmd:
        enabled: true
    fixme:
        enabled: true

exclude_paths:
    - *
    - .git/**/*
    - vendor/**/*
    - tests/**/*
